### ISSUE TITLE
how can I run any commands which is not in this image?

### ISSUE THREAD

**Issue by billwang-au** [jenkinsci/docker-slave#121]
Since the image is run as user/group of `jenkins`, I can't update and install any tools, such as python, node. 

```
$ docker run -ti --rm jenkins/jnlp-slave bash
jenkins@290f78c72661:~$ apt upgrade
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

```
$ docker run -ti --rm jenkins/jnlp-slave:alpine bash
bash-4.4$ apk update
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
bash-4.4$
```'
what should I do?

**Comment by oleg-nenashev** [comment]
If you want to add tools to an image, you should extend it. Doing package management in runtime is doable in principle if you run image as a root user, but it is not recommended

**Comment by billwang-au** [comment]
But this is slave (jenkins agent). Not sure how others did. 

Could you give me some hints, if I need run node or python in jenkins agent (slave), what should I do?

**Comment by billwang-au** [comment]
Close it, because it should be belong to https://github.com/jenkinsci/docker-jnlp-slave
