### ISSUE TITLE
LTS uses remoting 3.13

### ISSUE THREAD

**Issue by JonCubed** [jenkinsci/docker-slave#23]
LTS currently uses remoting 3.13, any chance we could get a container for that version?

**Comment by oleg-nenashev** [comment]
I had no plan for that. Using images with remoting 3.15 would be
recommended, 3.16 may fail fail in some cases due to stricter blacklist
(see JEP-200)

**Comment by JonCubed** [comment]
looking at the [remoting changelog](https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md), 3.15 can only be used with Jenkins 2.98 or higher. The [current LTS](https://jenkins.io/changelog-stable/) is 2.89.3 which would require 3.13.

It would be greatly appreciated if you could push a compatible version for LTS not just weekly

**Comment by oleg-nenashev** [comment]
Remiting 3.15 can be used even with Jenkins 1.x. The Jenkins version in
Remoting changelog just indicates version which bundles the Remiting
release in WAR.

**Comment by JonCubed** [comment]
ok documentation lead me to believe you need to use the version that matches the server you use.

I'll try 3.15 then.

**Comment by oleg-nenashev** [comment]
I will see if I can update the documentation. It would be great if you could create a JIRA ticket and mention the documentation sections which misled you. Thanks in advance

**Comment by JonCubed** [comment]
I'll see if I can find it again
