### ISSUE TITLE
USER ${user} doesn't allow for downstream package installation

### ISSUE THREAD

**Issue by jkarns87** [jenkinsci/docker-slave#31]
I'm trying to build customized JNLP Jenkins Containers for various processes which need to install additional packages. Having the USER ${user} switches the current user over to an unprivileged jenkins user which doesn't allow for package installation.

This is not an issue with the ssh-slave docker container because it is not utilizing this as an upstream.

**Comment by carlossg** [comment]
just do 

```
USER root
install packages
USER ${user}
```
