### ISSUE TITLE
Permission denied when executing "docker" command in Kubernetes configuration

### ISSUE THREAD

**Issue by natthapolvanasrivilai** [jenkinsci/docker-slave#37]
https://github.com/jenkinsci/docker-slave/blob/27b613551a5230a2f42e9e1097d6977e2892a3eb/Dockerfile#L26-L29

docker command will failed because the jenkins host has uid/gid of 1000, whereas the slave pod is running "jenkins" user on uid/gid 10000.

**Comment by carlossg** [comment]
you have to map users to your docker containers if you want, see docker/kubernetes docs
