### ISSUE TITLE
Change uid/gid made downstream ci failed

### ISSUE THREAD

**Issue by zhouqiang-cl** [jenkinsci/docker-slave#53]
Thank you for your greate job for docker-slave

But changes of https://github.com/jenkinsci/docker-slave/commit/19215a4806cf1a90c0991cf44f72db373f19e869 will make some user's CI/CD system fail

**Comment by slide** [comment]
You can override using --build-arg uid=10000 --build-arg gid=10000 if needed. According to the commit, this change was made to make the agent image more consistent with the master docker image. It's not ideal to make this sort of change, but sometimes it can be necessary.

**Comment by zhouqiang-cl** [comment]
got，thx
