### ISSUE TITLE
Slave remote version doesn't match master

### ISSUE THREAD

**Issue by eran-davidi-optibus** [jenkinsci/docker-slave#55]
Slave remote version is 3.27 while the master version is 3.29, this is causing Jenkins to put those agents on offline and not use them again.

This is urgent please create a slave image for 3.29.

Thank you
![image](https://user-images.githubusercontent.com/30209878/56891020-c3d09e80-6a83-11e9-9e13-be546345dea7.png)

**Comment by eran-davidi-optibus** [comment]
Thank you,
Can you please update jenkins/jnlp-slave on Dockerhub as well?

**Comment by oleg-nenashev** [comment]
Currently all DockerHub auto builds are unstable due to https://issues.jenkins-ci.org/browse/INFRA-2022 and other issues. We need to rework the agent Docker image delivery flow in the community. Right now all automatic builds may succeed or fail depending on your luck.

CC @carlossg
