### ISSUE TITLE
Introduce smoke tests in the Jenkinsfile

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkinsci/docker-slave#83]
Just to avoid issues when images are completely broken like in 3.35-1. https://github.com/jenkinsci/docker-slave/pull/82 for the fix.

Basically it would be great to have a test which just invokes `-help` on Remoting ans checks that the version is returned

**Comment by slide** [comment]
remoting.jar doesn't seem to have a `-help` option right now, though if you pass `-help` it prints the usage info with a `"-help" is not a valid option` message. It would be nice to add a `-version` command line argument.

**Comment by szandala** [comment]
I have started working on it:
https://github.com/jenkinsci/docker-slave/pull/90
we can use jarsigned -verify 'JARPATH'

Since I cannot test Jenkinsfile, I will set up my own Jenkins test and reply here

**Comment by slide** [comment]
I have some work done on this as well. I will push to a branch on my repo if you are interested.

**Comment by szandala** [comment]
yes, please. Link it to me

czw., 3 paź 2019 o 22:24 Alex Earl <notifications@github.com> napisał(a):

**Comment by slide** [comment]
https://github.com/slide/docker-slave/tree/smoketests

**Comment by oleg-nenashev** [comment]
#101 addressed it IIUC

**Comment by slide** [comment]
Yes, I think we can close this out.
